"""add subjects json field to users

Revision ID: 2023082803
Revises: 2023082801
Create Date: 2023-08-28 03:00:00.000000

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects.postgresql import JSONB

# revision identifiers, used by Alembic.
revision: str = '2023082803'
down_revision: Union[str, None] = None  # 设置为 None 表示这是第一个迁移
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # 删除旧的科目相关表
    op.drop_table('user_subject')
    op.drop_table('subjects')
    
    # 添加新的 subjects JSON 字段到 users 表
    op.add_column('users', sa.Column('subjects', JSONB, nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # 删除 subjects 字段
    op.drop_column('users', 'subjects')
    
    # 重新创建科目相关表
    op.create_table('subjects',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('name', sa.String(length=100), nullable=False),
        sa.Column('description', sa.Text(), nullable=True),
        sa.Column('created_at', sa.DateTime(), nullable=True),
        sa.Column('updated_at', sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_subjects_name'), 'subjects', ['name'], unique=True)
    
    op.create_table('user_subject',
        sa.Column('user_id', sa.Integer(), nullable=False),
        sa.Column('subject_id', sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(['subject_id'], ['subjects.id'], ondelete='CASCADE'),
        sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
        sa.PrimaryKeyConstraint('user_id', 'subject_id')
    )
    # ### end Alembic commands ###
