"""Recreate migration

Revision ID: e998662a8347
Revises: 
Create Date: 2025-11-19 14:06:06.150060

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'e998662a8347'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('related_knowledge')
    op.drop_table('subject_applications')
    op.drop_table('prerequisite_knowledge')
    op.drop_table('next_knowledge')
    op.drop_index(op.f('ix_operation_logs_id'), table_name='operation_logs')
    op.drop_table('operation_logs')
    op.drop_table('class_applications')
    op.create_index('idx_kpc_ancestor', 'knowledge_point_closure', ['ancestor_id'], unique=False)
    op.create_index('idx_kpc_descendant', 'knowledge_point_closure', ['descendant_id'], unique=False)
    op.drop_constraint(op.f('knowledge_point_closure_ancestor_id_fkey'), 'knowledge_point_closure', type_='foreignkey')
    op.drop_constraint(op.f('knowledge_point_closure_descendant_id_fkey'), 'knowledge_point_closure', type_='foreignkey')
    op.create_foreign_key(None, 'knowledge_point_closure', 'knowledge_points', ['ancestor_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'knowledge_point_closure', 'knowledge_points', ['descendant_id'], ['id'], ondelete='CASCADE')
    op.add_column('knowledge_points', sa.Column('code', sa.String(length=50), nullable=True, comment='知识点编码(格式:学科代码-学段代码-序号)'))
    # Fill default values for code column
    op.execute("UPDATE knowledge_points SET code = CONCAT('KP-', id) WHERE code IS NULL")
    op.alter_column('knowledge_points', 'code', nullable=False)
    op.add_column('knowledge_points', sa.Column('slug', sa.String(length=255), nullable=True, comment='URL友好的标识符'))
    # Fill default values for slug column
    op.execute("UPDATE knowledge_points SET slug = LOWER(REPLACE(name, ' ', '-')) WHERE slug IS NULL")
    op.alter_column('knowledge_points', 'slug', nullable=False)
    op.add_column('knowledge_points', sa.Column('domain', sa.String(length=100), nullable=True, comment='领域(如:数与代数)'))
    op.add_column('knowledge_points', sa.Column('topic', sa.String(length=100), nullable=True, comment='主题(如:函数)'))
    op.add_column('knowledge_points', sa.Column('grade_level', sa.String(length=50), nullable=True, comment='学段(如:初中三年级)'))
    op.add_column('knowledge_points', sa.Column('difficulty', sa.Integer(), nullable=True, comment='难度等级(1-5)'))
    op.add_column('knowledge_points', sa.Column('teaching_requirement', sa.Enum('UNDERSTAND', 'COMPREHEND', 'MASTER', 'APPLY', name='teachingrequirement'), nullable=True, comment='教学要求'))
    op.add_column('knowledge_points', sa.Column('exam_frequency', sa.Enum('LOW', 'MEDIUM', 'HIGH', 'VERY_HIGH', name='examfrequency'), nullable=True, comment='考查频率'))
    op.add_column('knowledge_points', sa.Column('learning_duration', sa.Integer(), nullable=True, comment='学习时长(分钟)'))
    op.add_column('knowledge_points', sa.Column('is_key_point', sa.Boolean(), nullable=True, comment='是否为重点知识点'))
    op.add_column('knowledge_points', sa.Column('is_difficulty_point', sa.Boolean(), nullable=True, comment='是否为难点'))
    op.add_column('knowledge_points', sa.Column('is_error_prone', sa.Boolean(), nullable=True, comment='是否易错'))
    op.add_column('knowledge_points', sa.Column('status', sa.Enum('DRAFT', 'PENDING_REVIEW', 'APPROVED', 'PUBLISHED', 'ARCHIVED', 'DELETED', name='versionstatus'), nullable=True, comment='知识点状态'))
    op.add_column('knowledge_points', sa.Column('version', sa.String(length=50), nullable=True, comment='当前版本号'))
    op.add_column('knowledge_points', sa.Column('is_active', sa.Boolean(), nullable=True, comment='是否启用'))
    op.add_column('knowledge_points', sa.Column('weight', sa.Float(), nullable=True, comment='知识点权重'))
    # Fill default values for new NOT NULL columns
    op.execute("UPDATE knowledge_points SET difficulty = 3 WHERE difficulty IS NULL")
    op.execute("UPDATE knowledge_points SET teaching_requirement = 'MASTER' WHERE teaching_requirement IS NULL")
    op.execute("UPDATE knowledge_points SET exam_frequency = 'MEDIUM' WHERE exam_frequency IS NULL")
    op.execute("UPDATE knowledge_points SET is_key_point = false WHERE is_key_point IS NULL")
    op.execute("UPDATE knowledge_points SET is_difficulty_point = false WHERE is_difficulty_point IS NULL")
    op.execute("UPDATE knowledge_points SET is_error_prone = false WHERE is_error_prone IS NULL")
    op.execute("UPDATE knowledge_points SET status = 'PUBLISHED' WHERE status IS NULL")
    op.execute("UPDATE knowledge_points SET version = 'v1.0.0' WHERE version IS NULL")
    op.execute("UPDATE knowledge_points SET is_active = true WHERE is_active IS NULL")
    op.execute("UPDATE knowledge_points SET weight = 1.0 WHERE weight IS NULL")
    # Alter columns to NOT NULL
    op.alter_column('knowledge_points', 'difficulty', nullable=False)
    op.alter_column('knowledge_points', 'teaching_requirement', nullable=False)
    op.alter_column('knowledge_points', 'exam_frequency', nullable=False)
    op.alter_column('knowledge_points', 'is_key_point', nullable=False)
    op.alter_column('knowledge_points', 'is_difficulty_point', nullable=False)
    op.alter_column('knowledge_points', 'is_error_prone', nullable=False)
    op.alter_column('knowledge_points', 'status', nullable=False)
    op.alter_column('knowledge_points', 'version', nullable=False)
    op.alter_column('knowledge_points', 'is_active', nullable=False)
    op.alter_column('knowledge_points', 'weight', nullable=False)
    op.add_column('knowledge_points', sa.Column('metadata_', sa.JSON(), nullable=True, comment='自定义属性'))
    op.add_column('knowledge_points', sa.Column('created_by', sa.String(length=100), nullable=True, comment='创建人'))
    op.add_column('knowledge_points', sa.Column('updated_by', sa.String(length=100), nullable=True, comment='修改人'))
    op.add_column('knowledge_points', sa.Column('reviewed_by', sa.String(length=100), nullable=True, comment='审核人'))
    op.add_column('knowledge_points', sa.Column('reviewed_at', sa.DateTime(), nullable=True, comment='审核时间'))
    op.alter_column('knowledge_points', 'name',
               existing_type=sa.VARCHAR(length=100),
               type_=sa.String(length=200),
               existing_comment='知识点名称',
               existing_nullable=False)
    op.alter_column('knowledge_points', 'description',
               existing_type=sa.TEXT(),
               nullable=False,
               comment='知识点描述',
               existing_comment='简短描述')
    op.alter_column('knowledge_points', 'subject_id',
               existing_type=sa.INTEGER(),
               comment='所属学科ID',
               existing_nullable=False)
    op.alter_column('knowledge_points', 'parent_id',
               existing_type=sa.INTEGER(),
               comment='父知识点ID',
               existing_nullable=True)
    op.alter_column('knowledge_points', 'depth',
               existing_type=sa.INTEGER(),
               nullable=False,
               comment='知识点深度(用于快速查询)')
    op.alter_column('knowledge_points', 'path',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.String(length=1024),
               comment='层级路径(如 1/3/5)',
               existing_nullable=True)
    op.alter_column('knowledge_points', 'tags',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               comment='知识点标签',
               existing_comment='关键词/标签',
               existing_nullable=True)
    op.alter_column('knowledge_points', 'creator_id',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_comment='创建者ID')
    op.alter_column('knowledge_points', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    op.alter_column('knowledge_points', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    op.drop_index(op.f('ix_knowledge_points_parent_id'), table_name='knowledge_points')
    op.drop_index(op.f('ix_knowledge_points_path'), table_name='knowledge_points')
    op.create_index('idx_kp_code', 'knowledge_points', ['code'], unique=False)
    op.create_index('idx_kp_grade_level', 'knowledge_points', ['grade_level'], unique=False)
    op.create_index('idx_kp_name', 'knowledge_points', ['name'], unique=False)
    op.create_index('idx_kp_slug', 'knowledge_points', ['slug'], unique=False)
    op.create_index('idx_kp_status', 'knowledge_points', ['status'], unique=False)
    op.create_index('idx_kp_subject_id', 'knowledge_points', ['subject_id'], unique=False)
    op.create_index(op.f('ix_knowledge_points_slug'), 'knowledge_points', ['slug'], unique=True)
    op.create_unique_constraint('uq_kp_subject_name', 'knowledge_points', ['subject_id', 'name'])
    op.create_unique_constraint(None, 'knowledge_points', ['code'])
    op.drop_column('knowledge_points', 'learning_suggestions')
    op.drop_column('knowledge_points', 'difficulty_level')
    op.drop_column('knowledge_points', 'content')
    op.drop_column('knowledge_points', 'estimated_time')
    op.drop_column('knowledge_points', 'tree_position')
    op.drop_column('knowledge_points', 'media_urls')
    op.drop_column('knowledge_points', 'learning_objectives')
    op.drop_column('knowledge_points', 'examples')
    op.drop_column('knowledge_points', 'source')
    op.drop_column('knowledge_points', 'media_type')
    op.create_foreign_key(None, 'question_tags', 'tags', ['tag_id'], ['id'])
    op.add_column('question_vectors', sa.Column('updated_at', sa.DateTime(), nullable=False))
    op.drop_index(op.f('ix_question_vectors_embedding'), table_name='question_vectors', postgresql_using='ivfflat')
    op.create_index(op.f('ix_question_vectors_id'), 'question_vectors', ['id'], unique=False)
    op.drop_constraint(op.f('question_vectors_subject_id_fkey'), 'question_vectors', type_='foreignkey')
    op.drop_constraint(op.f('question_vectors_user_id_fkey'), 'question_vectors', type_='foreignkey')
    op.create_foreign_key(None, 'question_vectors', 'subjects', ['subject_id'], ['id'])
    op.create_foreign_key(None, 'question_vectors', 'users', ['user_id'], ['id'])
    op.alter_column('questions', 'knowledge_point_ids',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               comment='关联知识点ID列表',
               existing_nullable=False,
               existing_server_default=sa.text("'[]'::json"))
    op.drop_column('questions', 'knowledge_points')
    op.alter_column('resources', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_constraint(op.f('fk_resources_user_id'), 'resources', type_='foreignkey')
    op.create_foreign_key(None, 'resources', 'users', ['user_id'], ['id'])
    # Fill default values for subjects table
    op.execute("UPDATE subjects SET creator_id = 2 WHERE creator_id IS NULL")
    op.alter_column('subjects', 'creator_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('subjects', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    op.alter_column('subjects', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    op.drop_constraint(op.f('fk_subjects_creator_id'), 'subjects', type_='foreignkey')
    op.drop_constraint(op.f('fk_subjects_user_id'), 'subjects', type_='foreignkey')
    op.create_foreign_key(None, 'subjects', 'users', ['creator_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'subjects', type_='foreignkey')
    op.create_foreign_key(op.f('fk_subjects_user_id'), 'subjects', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(op.f('fk_subjects_creator_id'), 'subjects', 'users', ['creator_id'], ['id'], ondelete='CASCADE')
    op.alter_column('subjects', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.alter_column('subjects', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.alter_column('subjects', 'creator_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_constraint(None, 'resources', type_='foreignkey')
    op.create_foreign_key(op.f('fk_resources_user_id'), 'resources', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.alter_column('resources', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.add_column('questions', sa.Column('knowledge_points', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.alter_column('questions', 'knowledge_point_ids',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               comment=None,
               existing_comment='关联知识点ID列表',
               existing_nullable=False,
               existing_server_default=sa.text("'[]'::json"))
    op.drop_constraint(None, 'question_vectors', type_='foreignkey')
    op.drop_constraint(None, 'question_vectors', type_='foreignkey')
    op.create_foreign_key(op.f('question_vectors_user_id_fkey'), 'question_vectors', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(op.f('question_vectors_subject_id_fkey'), 'question_vectors', 'subjects', ['subject_id'], ['id'], ondelete='SET NULL')
    op.drop_index(op.f('ix_question_vectors_id'), table_name='question_vectors')
    op.create_index(op.f('ix_question_vectors_embedding'), 'question_vectors', ['embedding'], unique=False, postgresql_using='ivfflat')
    op.drop_column('question_vectors', 'updated_at')
    op.drop_constraint(None, 'question_tags', type_='foreignkey')
    op.add_column('knowledge_points', sa.Column('media_type', postgresql.ENUM('TEXT', 'IMAGE', 'AUDIO', 'VIDEO', 'ANIMATION', name='mediatype'), autoincrement=False, nullable=True, comment='主要媒体类型'))
    op.add_column('knowledge_points', sa.Column('source', sa.VARCHAR(length=200), autoincrement=False, nullable=True, comment='知识点来源'))
    op.add_column('knowledge_points', sa.Column('examples', sa.TEXT(), autoincrement=False, nullable=True, comment='典型案例或具体实例'))
    op.add_column('knowledge_points', sa.Column('learning_objectives', sa.TEXT(), autoincrement=False, nullable=True, comment='学习目标'))
    op.add_column('knowledge_points', sa.Column('media_urls', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True, comment='媒体资源URLs'))
    op.add_column('knowledge_points', sa.Column('tree_position', sa.VARCHAR(length=100), autoincrement=False, nullable=True, comment='在知识树中的位置编码'))
    op.add_column('knowledge_points', sa.Column('estimated_time', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True, comment='预计学习时间(分钟)'))
    op.add_column('knowledge_points', sa.Column('content', sa.TEXT(), autoincrement=False, nullable=True, comment='核心讲解内容'))
    op.add_column('knowledge_points', sa.Column('difficulty_level', postgresql.ENUM('BASIC', 'INTERMEDIATE', 'ADVANCED', name='difficultylevel'), autoincrement=False, nullable=True, comment='难度等级'))
    op.add_column('knowledge_points', sa.Column('learning_suggestions', sa.TEXT(), autoincrement=False, nullable=True, comment='学习建议'))
    op.drop_constraint(None, 'knowledge_points', type_='unique')
    op.drop_constraint('uq_kp_subject_name', 'knowledge_points', type_='unique')
    op.drop_index(op.f('ix_knowledge_points_slug'), table_name='knowledge_points')
    op.drop_index('idx_kp_subject_id', table_name='knowledge_points')
    op.drop_index('idx_kp_status', table_name='knowledge_points')
    op.drop_index('idx_kp_slug', table_name='knowledge_points')
    op.drop_index('idx_kp_name', table_name='knowledge_points')
    op.drop_index('idx_kp_grade_level', table_name='knowledge_points')
    op.drop_index('idx_kp_code', table_name='knowledge_points')
    op.create_index(op.f('ix_knowledge_points_path'), 'knowledge_points', ['path'], unique=False)
    op.create_index(op.f('ix_knowledge_points_parent_id'), 'knowledge_points', ['parent_id'], unique=False)
    op.alter_column('knowledge_points', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.alter_column('knowledge_points', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.alter_column('knowledge_points', 'creator_id',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_comment='创建者ID')
    op.alter_column('knowledge_points', 'tags',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               comment='关键词/标签',
               existing_comment='知识点标签',
               existing_nullable=True)
    op.alter_column('knowledge_points', 'path',
               existing_type=sa.String(length=1024),
               type_=sa.VARCHAR(length=255),
               comment=None,
               existing_comment='层级路径(如 1/3/5)',
               existing_nullable=True)
    op.alter_column('knowledge_points', 'depth',
               existing_type=sa.INTEGER(),
               nullable=True,
               comment=None,
               existing_comment='知识点深度(用于快速查询)')
    op.alter_column('knowledge_points', 'parent_id',
               existing_type=sa.INTEGER(),
               comment=None,
               existing_comment='父知识点ID',
               existing_nullable=True)
    op.alter_column('knowledge_points', 'subject_id',
               existing_type=sa.INTEGER(),
               comment=None,
               existing_comment='所属学科ID',
               existing_nullable=False)
    op.alter_column('knowledge_points', 'description',
               existing_type=sa.TEXT(),
               nullable=True,
               comment='简短描述',
               existing_comment='知识点描述')
    op.alter_column('knowledge_points', 'name',
               existing_type=sa.String(length=200),
               type_=sa.VARCHAR(length=100),
               existing_comment='知识点名称',
               existing_nullable=False)
    op.drop_column('knowledge_points', 'reviewed_at')
    op.drop_column('knowledge_points', 'reviewed_by')
    op.drop_column('knowledge_points', 'updated_by')
    op.drop_column('knowledge_points', 'created_by')
    op.drop_column('knowledge_points', 'metadata_')
    op.drop_column('knowledge_points', 'weight')
    op.drop_column('knowledge_points', 'is_active')
    op.drop_column('knowledge_points', 'version')
    op.drop_column('knowledge_points', 'status')
    op.drop_column('knowledge_points', 'is_error_prone')
    op.drop_column('knowledge_points', 'is_difficulty_point')
    op.drop_column('knowledge_points', 'is_key_point')
    op.drop_column('knowledge_points', 'learning_duration')
    op.drop_column('knowledge_points', 'exam_frequency')
    op.drop_column('knowledge_points', 'teaching_requirement')
    op.drop_column('knowledge_points', 'difficulty')
    op.drop_column('knowledge_points', 'grade_level')
    op.drop_column('knowledge_points', 'topic')
    op.drop_column('knowledge_points', 'domain')
    op.drop_column('knowledge_points', 'slug')
    op.drop_column('knowledge_points', 'code')
    op.drop_constraint(None, 'knowledge_point_closure', type_='foreignkey')
    op.drop_constraint(None, 'knowledge_point_closure', type_='foreignkey')
    op.create_foreign_key(op.f('knowledge_point_closure_descendant_id_fkey'), 'knowledge_point_closure', 'knowledge_points', ['descendant_id'], ['id'])
    op.create_foreign_key(op.f('knowledge_point_closure_ancestor_id_fkey'), 'knowledge_point_closure', 'knowledge_points', ['ancestor_id'], ['id'])
    op.drop_index('idx_kpc_descendant', table_name='knowledge_point_closure')
    op.drop_index('idx_kpc_ancestor', table_name='knowledge_point_closure')
    op.create_table('class_applications',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('class_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('applicant_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('status', postgresql.ENUM('PENDING', 'APPROVED', 'REJECTED', name='applicationstatus'), autoincrement=False, nullable=True),
    sa.Column('message', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['applicant_id'], ['users.id'], name=op.f('class_applications_applicant_id_fkey'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['class_id'], ['classes.id'], name=op.f('class_applications_class_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('class_applications_pkey'))
    )
    op.create_table('operation_logs',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('timestamp', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('operation', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('path', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('method', sa.VARCHAR(length=10), autoincrement=False, nullable=True),
    sa.Column('ip_address', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('details', sa.VARCHAR(length=500), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('operation_logs_user_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('operation_logs_pkey'))
    )
    op.create_index(op.f('ix_operation_logs_id'), 'operation_logs', ['id'], unique=False)
    op.create_table('next_knowledge',
    sa.Column('knowledge_point_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('next_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['knowledge_point_id'], ['knowledge_points.id'], name=op.f('next_knowledge_knowledge_point_id_fkey')),
    sa.ForeignKeyConstraint(['next_id'], ['knowledge_points.id'], name=op.f('next_knowledge_next_id_fkey')),
    sa.PrimaryKeyConstraint('knowledge_point_id', 'next_id', name=op.f('next_knowledge_pkey'))
    )
    op.create_table('prerequisite_knowledge',
    sa.Column('knowledge_point_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('prerequisite_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['knowledge_point_id'], ['knowledge_points.id'], name=op.f('prerequisite_knowledge_knowledge_point_id_fkey')),
    sa.ForeignKeyConstraint(['prerequisite_id'], ['knowledge_points.id'], name=op.f('prerequisite_knowledge_prerequisite_id_fkey')),
    sa.PrimaryKeyConstraint('knowledge_point_id', 'prerequisite_id', name=op.f('prerequisite_knowledge_pkey'))
    )
    op.create_table('subject_applications',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('subject_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('applicant_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('status', postgresql.ENUM('PENDING', 'APPROVED', 'REJECTED', name='applicationstatus'), autoincrement=False, nullable=True),
    sa.Column('message', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['applicant_id'], ['users.id'], name=op.f('subject_applications_applicant_id_fkey'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['subject_id'], ['subjects.id'], name=op.f('subject_applications_subject_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('subject_applications_pkey'))
    )
    op.create_table('related_knowledge',
    sa.Column('knowledge_point_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('related_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['knowledge_point_id'], ['knowledge_points.id'], name=op.f('related_knowledge_knowledge_point_id_fkey')),
    sa.ForeignKeyConstraint(['related_id'], ['knowledge_points.id'], name=op.f('related_knowledge_related_id_fkey')),
    sa.PrimaryKeyConstraint('knowledge_point_id', 'related_id', name=op.f('related_knowledge_pkey'))
    )
    # ### end Alembic commands ###
